services:
  # ─── Public Web Services ──────────────────────────────────────────

  - type: web
    name: api-gateway
    plan: free
    env: node
    buildCommand: npm install && npx nx build api-gateway
    startCommand: node dist/apps/api-gateway/main.js
    envVars:
      - key: JWT_SECRET
        value: "super-secret-local-jwt-key"
      - key: AUTH_SERVICE_HOST
        fromService:
          type: web
          name: auth-service
          property: host
      - key: USER_SERVICE_HOST
        fromService:
          type: web
          name: user-service
          property: host
      - key: COURSE_SERVICE_HOST
        fromService:
          type: web
          name: course-service
          property: host
      - key: MEDIA_SERVICE_HOST
        fromService:
          type: web
          name: media-service
          property: host

  # ─── Hybrid Web Services (gRPC + HTTP) ─────────────────────────────────
  - type: web
    name: auth-service
    plan: free
    env: node
    buildCommand: npm install && npx nx build auth-service
    startCommand: node dist/apps/auth-service/main.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_n9Db2XMrocVZ@ep-crimson-river-axxww90y-pooler.c-4.us-east-2.aws.neon.tech/AuthDB?sslmode=require&uselibpqcompat=true&channel_binding=require"
      - key: JWT_SECRET
        value: "super-secret-local-jwt-key"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "iamakashkumar2007@gmail.com"
      - key: SMTP_PASS
        value: "trgzecgkbbeobfgk"
      - key: USER_SERVICE_HOST
        fromService:
          type: web
          name: user-service
          property: host

  - type: web
    name: user-service
    plan: free
    env: node
    buildCommand: npm install && npx nx build user-service
    startCommand: node dist/apps/user-service/main.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_n9Db2XMrocVZ@ep-crimson-river-axxww90y-pooler.c-4.us-east-2.aws.neon.tech/Userdb?sslmode=require&uselibpqcompat=true&channel_binding=require"

  - type: web
    name: course-service
    plan: free
    env: node
    buildCommand: npm install && npx nx build course-service
    startCommand: node dist/apps/course-service/main.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_n9Db2XMrocVZ@ep-crimson-river-axxww90y-pooler.c-4.us-east-2.aws.neon.tech/CourseDB?sslmode=require&channel_binding=require"

  - type: web
    name: media-service
    plan: free
    env: node
    buildCommand: npm install && npx nx build media-service
    startCommand: node dist/apps/media-service/main.js
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_n9Db2XMrocVZ@ep-crimson-river-axxww90y-pooler.c-4.us-east-2.aws.neon.tech/MediaDB?sslmode=require&channel_binding=require"
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_REFRESH_TOKEN
        sync: false
