syntax = "proto3";

package user;

service UserService {
  rpc GetProfile (GetProfileRequest) returns (GetProfileResponse) {}
  rpc UpdateProfile (UpdateProfileRequest) returns (UpdateProfileResponse) {}
}

message GetProfileRequest {
  string userId = 1;
}

message GetProfileResponse {
  string userId = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
  string role = 5;

  // Student specific fields
  optional string bio = 6;
  optional string learningGoals = 7;
  optional string interests = 8;

  // Instructor specific fields
  optional string headline = 9;
  optional string biography = 10;
  optional string website = 11;
  optional string socialLinks = 12;
}

message UpdateProfileRequest {
  string userId = 1;
  string firstName = 2;
  string lastName = 3;
  string role = 4;
  optional string email = 5;

  // Student specific fields
  optional string bio = 6;
  optional string learningGoals = 7;
  optional string interests = 8;

  // Instructor specific fields
  optional string headline = 9;
  optional string biography = 10;
  optional string website = 11;
  optional string socialLinks = 12;
}

message UpdateProfileResponse {
  bool success = 1;
  string message = 2;
}
